version: '3.8'

services:
  django:
    build: ./djchat
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djchat:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env

  redis:
    image: redis:alpine
    volumes:
      - ./redis_data:/data
